app:
  name: payments-web

server:
  port: 19000
  session:
    timeout: 12
  compression:
     enabled: true
     mime-types: application/json,application/xml,text/html,text/xml,text/plain    
  tomcat:
    uri-encoding: UTF-8
    max-http-form-post-size: 200MB
    max-swallow-size: 200MB 
  
  servlet:      
    encoding:
      charset: UTF-8
      enabled: true
      force: true      
    jsp:
      init-parameters:
        development: true      
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  devtools:
    livereload:
      enabled: true
      
  resources:
    static-locations: file:./src/main/webapp/WEB-INF/resources
               
  datasource:
    hikari:
      primary: 
         driver-class-name: "org.mariadb.jdbc.Driver"
         jdbc_url: "jdbc:mariadb://127.0.0.1:3306/bizbooks?allowMultiQueries=true&characterEncoding=utf-8"
         username: "newzen"
         password: "!@#sbwps09#"
         maximumPoolSize: 2
         max-active: 2
         max-idle: 2
         min-idle: 2
         initial-size: 2
         test-on-borrow: "true"
         test-on-return: "true"
         idleTimeout: 600000
         max-lifetime: 2000000
         connection-timeout: 30000
         validation-timeout: 50000
         auto-commit: "true"
         poolName: ${app.name}

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      location: ${java.io.tmpdir}
  
#logging:
  #config: classpath:config/localhost/logback.xml